import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CircleStop, LoaderCircle, Radio, RefreshCw, Share2, ShoppingBag } from "lucide-react";
import type { CommerceWorkspaceAdapter, Conversion, ProductQueue, StudioSessionState, StudioStatus } from "../../contracts";
import { Button } from "../../components/ui/button";
import "./SellWorkspace.css";

export interface SellWorkspaceProps { adapter: CommerceWorkspaceAdapter; authenticated: boolean; mode: "native" | "preview"; selectedProductId: string | null; onSelectProduct(id: string): void; onOpenShop(): void; onShare(productId: string): void; onSessionChange?(session: StudioSessionState | null): void; locale?: "en" | "fr"; }
type Phase = "loading" | "ready" | "locked" | "preview" | "error";
type Operation = "start" | "stop" | null;
const messages = { en: { eyebrow: "SELL / LIVE STUDIO", title: "Run the room, keep the sale moving.", preview: "Live controls require the Yaatal desktop app.", locked: "Sign in to prepare your Studio session.", loading: "Recovering your Studio session…", retry: "Try again", readiness: "Studio readiness", queue: "Product queue", noProducts: "No products are queued for this live session.", openShop: "Open in Shop", share: "Share", start: "Go live", starting: "Starting live…", stop: "Stop stream", stopping: "Stopping stream…", live: "Live now", offAir: "Not live", started: "Started", conversions: "Attributed conversions", noConversions: "No conversions for this session yet.", sandbox: "Sandbox paid", unavailable: "Studio is unavailable. Try again.", auth: "Studio access is not available for this account.", lastSession: "Last session", noSession: "Start a live session to see attributed conversions.", reload: "Refresh Studio", source: "Source" }, fr: { eyebrow: "VENDRE / STUDIO DIRECT", title: "Animez le direct, gardez la vente en mouvement.", preview: "Les commandes de direct nécessitent l’application de bureau Yaatal.", locked: "Connectez-vous pour préparer votre session Studio.", loading: "Récupération de votre session Studio…", retry: "Réessayer", readiness: "État du Studio", queue: "File de produits", noProducts: "Aucun produit n’est dans la file de ce direct.", openShop: "Ouvrir dans la boutique", share: "Partager", start: "Lancer le direct", starting: "Lancement du direct…", stop: "Arrêter le direct", stopping: "Arrêt du direct…", live: "En direct", offAir: "Hors direct", started: "Démarré", conversions: "Conversions attribuées", noConversions: "Aucune conversion pour cette session.", sandbox: "Paiement test", unavailable: "Le Studio est indisponible. Réessayez.", auth: "L’accès au Studio n’est pas disponible pour ce compte.", lastSession: "Dernière session", noSession: "Lancez un direct pour voir les conversions attribuées.", reload: "Actualiser le Studio", source: "Source" } } as const;
function errorText(error: unknown, fallback: string) { return error instanceof Error && error.message ? error.message : fallback; }
function dedupe(values: Conversion[]) { const seen = new Set<string>(); return values.filter(value => !seen.has(value.orderId) && (seen.add(value.orderId), true)); }
function elapsed(startedAt: number, now: number) { const seconds = Math.max(0, Math.floor((now - startedAt * 1_000) / 1_000)); return [Math.floor(seconds / 3_600), Math.floor(seconds / 60) % 60, seconds % 60].map(value => String(value).padStart(2, "0")).join(":"); }

/** Shell wiring supplies the authenticated adapter and callbacks. Events remain a later native transport card; this component never polls. */
export function SellWorkspace({ adapter, authenticated, mode, selectedProductId, onSelectProduct, onOpenShop, onShare: sendShare, onSessionChange, locale = "en" }: SellWorkspaceProps) {
  const copy = messages[locale]; const [phase, setPhase] = useState<Phase>("loading"); const [session, setSession] = useState<StudioSessionState | null>(null); const [status, setStatus] = useState<StudioStatus | null>(null); const [queue, setQueue] = useState<ProductQueue | null>(null); const [retainedSessionId, setRetainedSessionId] = useState<string | null>(null); const [conversions, setConversions] = useState<Conversion[]>([]); const [conversionState, setConversionState] = useState<"idle" | "loading" | "ready" | "error">("idle"); const [error, setError] = useState(""); const [conversionError, setConversionError] = useState(""); const [operation, setOperation] = useState<Operation>(null); const [now, setNow] = useState(Date.now()); const [conversionRefresh, setConversionRefresh] = useState(0); const request = useRef(0); const conversionRequest = useRef(0);
  const clear = useCallback((next: Phase) => { setPhase(next); setSession(null); setStatus(null); setQueue(null); setRetainedSessionId(null); setConversions([]); setError(""); setOperation(null); }, []);
  const hydrate = useCallback(async () => { const version = ++request.current; setPhase("loading"); setError(""); try { const bootstrap = await adapter.bootstrap(); if (version !== request.current) return; if (!bootstrap.authenticated) { setPhase("locked"); setError(copy.auth); return; } const [nextSession, nextStatus, nextQueue] = await Promise.all([adapter.sessionState(), adapter.status(), adapter.productQueue()]); if (version !== request.current) return; setSession(nextSession); setStatus(nextStatus); setQueue(nextQueue); setRetainedSessionId(nextSession.sessionId); setPhase("ready"); } catch (failure) { if (version === request.current) { setPhase("error"); setError(errorText(failure, copy.unavailable)); } } }, [adapter, copy.auth, copy.unavailable]);
  useEffect(() => { request.current += 1; if (mode === "preview") { clear("preview"); return; } if (!authenticated) { clear("locked"); return; } void hydrate(); return () => { request.current += 1; conversionRequest.current += 1; }; }, [authenticated, clear, hydrate, mode]);
  const scope = session?.sessionId || retainedSessionId;
  useEffect(() => { if (!scope || phase !== "ready") { conversionRequest.current += 1; setConversions([]); setConversionState("idle"); setConversionError(""); return; } const version = ++conversionRequest.current; setConversionState("loading"); setConversionError(""); void adapter.conversions(scope).then(values => { if (version === conversionRequest.current) { setConversions(dedupe(values)); setConversionState("ready"); } }).catch(failure => { if (version === conversionRequest.current) { setConversions([]); setConversionState("error"); setConversionError(errorText(failure, copy.unavailable)); } }); return () => { conversionRequest.current += 1; }; }, [adapter, conversionRefresh, copy.unavailable, phase, scope]);
  useEffect(() => { onSessionChange?.(phase === "ready" ? session : null); }, [onSessionChange, phase, session]);
  useEffect(() => { if (!session?.isLive || !session.startedAt) return; const timer = window.setInterval(() => setNow(Date.now()), 1_000); return () => window.clearInterval(timer); }, [session?.isLive, session?.startedAt]);
  const control = useCallback(async (action: Exclude<Operation, null>) => { if (operation || phase !== "ready") return; const version = request.current; const currentScope = session?.sessionId || retainedSessionId; setOperation(action); setError(""); try { const next = action === "start" ? await adapter.goLive() : await adapter.stopStream(); if (version === request.current) { setSession(next); setRetainedSessionId(next.sessionId || currentScope || null); } } catch (failure) { if (version === request.current) setError(errorText(failure, copy.unavailable)); } finally { if (version === request.current) setOperation(null); } }, [adapter, copy.unavailable, operation, phase, retainedSessionId, session?.sessionId]);
  const onShare = useCallback((productId: string) => { const product = queue?.products.find(item => item.id === productId); if (authenticated && session?.isLive && product && product.stock > 0 && !/out[ -]?of[ -]?stock|sold[ -]?out|unavailable/i.test(product.stockStatus)) sendShare(productId); }, [authenticated, queue?.products, sendShare, session?.isLive]);
  const clock = useMemo(() => session?.isLive && session.startedAt ? elapsed(session.startedAt, now) : copy.offAir, [copy.offAir, now, session]);
  if (phase !== "ready") return <section className="sell-workspace sell-workspace--state" aria-labelledby="sell-heading"><p className="eyebrow">{copy.eyebrow}</p><h1 id="sell-heading">{copy.title}</h1><div className="sell-state" role={phase === "error" ? "alert" : "status"}>{phase === "loading" && <LoaderCircle className="sell-spinner" aria-hidden="true" size={20} />}<p>{phase === "preview" ? copy.preview : phase === "locked" ? error || copy.locked : phase === "loading" ? copy.loading : error}</p>{phase === "error" && <Button onClick={() => void hydrate()}><RefreshCw size={18} />{copy.retry}</Button>}</div></section>;
  const shareAvailable = (product: { stock: number; stockStatus: string }) => authenticated && Boolean(session?.isLive) && product.stock > 0 && !/out[ -]?of[ -]?stock|sold[ -]?out|unavailable/i.test(product.stockStatus);
  const conversionContent = !scope ? <p className="sell-empty">{copy.noSession}</p> : conversionState === "loading" ? <p className="sell-empty" role="status"><LoaderCircle className="sell-spinner" aria-hidden="true" size={18} />{copy.loading}</p> : conversionState === "error" ? <div className="sell-conversion-error" role="alert"><p>{conversionError}</p><Button variant="outline" onClick={() => setConversionRefresh(value => value + 1)}>{copy.retry}</Button></div> : conversions.length ? <ul>{conversions.map(conversion => <li key={conversion.orderId}><div><strong>{conversion.productName}</strong><span>{conversion.orderId} · {conversion.sourceChannel}</span></div><div><strong>{conversion.totalFcfa.toLocaleString(locale === "fr" ? "fr-SN" : "en-SN")} FCFA</strong><span>{conversion.paymentProvider} · {copy.sandbox}</span></div></li>)}</ul> : <p className="sell-empty">{copy.noConversions}</p>;
  return <section className="sell-workspace" aria-labelledby="sell-heading">
    <header className="sell-heading"><div><p className="eyebrow">{copy.eyebrow}</p><h1 id="sell-heading">{copy.title}</h1></div><div className={`sell-live-status ${session?.isLive ? "is-live" : ""}`} role="status"><i aria-hidden="true" />{session?.isLive ? copy.live : copy.offAir}</div></header>
    {error && <p className="sell-error" role="alert">{error}</p>}
    <div className="sell-layout">
      <section className="sell-live-card"><div className="sell-live-card__top"><div><p>{session?.sellerName || "Studio"}</p><strong>{clock}</strong></div><span>{copy.started}: {session?.startedAt ? new Date(session.startedAt * 1_000).toLocaleTimeString(locale === "fr" ? "fr-SN" : "en-SN", { hour: "numeric", minute: "2-digit" }) : "—"}</span></div><div className="sell-live-actions">{session?.isLive ? <Button disabled={operation !== null} onClick={() => void control("stop")}><CircleStop size={18} />{operation === "stop" ? copy.stopping : copy.stop}</Button> : <Button disabled={operation !== null} onClick={() => void control("start")}><Radio size={18} />{operation === "start" ? copy.starting : copy.start}</Button>}<Button variant="outline" disabled={operation !== null} onClick={() => void hydrate()}><RefreshCw size={18} />{copy.reload}</Button></div></section>
      <section className="sell-readiness"><div className="sell-section-heading"><h2>{copy.readiness}</h2><span>{status?.readiness.status || "—"}</span></div><ul>{status?.readiness.steps.map(step => <li key={step.name}><span>{step.name}</span><strong data-status={step.status}>{step.status}</strong>{step.durationMs !== undefined && <small>{step.durationMs} ms</small>}</li>)}</ul></section>
      <section className="sell-queue"><div className="sell-section-heading"><h2>{copy.queue}</h2>{queue && <span>{copy.source}: {queue.source}</span>}</div>{queue?.products.length ? <ul>{queue.products.map(product => <li key={product.id} className={selectedProductId === product.id ? "is-selected" : ""}><button type="button" onClick={() => onSelectProduct(product.id)}><span>{product.name}</span><strong>{product.priceDisplay}</strong></button><div><Button variant="ghost" onClick={() => { onSelectProduct(product.id); onOpenShop(); }}><ShoppingBag size={17} />{copy.openShop}</Button><Button variant="ghost" disabled={!shareAvailable(product)} onClick={() => onShare(product.id)}><Share2 size={17} />{copy.share}</Button></div></li>)}</ul> : <p className="sell-empty">{copy.noProducts}</p>}</section>
      <section className="sell-conversions"><div className="sell-section-heading"><h2>{copy.conversions}</h2>{scope && <span>{session?.isLive ? copy.live : copy.lastSession}</span>}</div>{conversionContent}</section>
    </div>
  </section>;
}
