import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, CircleStop, ImageOff, LoaderCircle, MicOff, Radio, RefreshCw, Share2, ShieldCheck, ShoppingBag } from "lucide-react";
import type { CommerceWorkspaceAdapter, Conversion, ProductQueue, StudioSessionState, StudioStatus } from "../../contracts";
import { Button } from "../../components/ui/button";
import "./SellWorkspace.css";

export interface SellWorkspaceProps { adapter: CommerceWorkspaceAdapter; authenticated: boolean; accountEpoch?: number; recoveryEpoch?: number; studioResetEpoch?: number; studioReady?: boolean; conversionInvalidation?: { liveSessionId: string; epoch: number } | null; mode: "native" | "preview"; selectedProductId: string | null; onSelectProduct(id: string): void; onOpenShop(): void; onShare(productId: string): void; onSessionChange?(session: StudioSessionState | null): void; locale?: "en" | "fr"; }
type Phase = "loading" | "ready" | "locked" | "preview" | "error";
type Operation = "start" | "stop" | null;
const messages = { en: { eyebrow: "SELL / LIVE STUDIO", title: "Live Studio", preview: "Live controls require the Yaatal desktop app.", locked: "Sign in to prepare your Studio session.", loading: "Recovering your Studio session…", retry: "Try again", readiness: "Studio readiness", queue: "Product queue", noProducts: "No products are queued for this live session.", openShop: "Open in SHOP", share: "Share", start: "Go live", starting: "Starting live…", stop: "Stop stream", stopping: "Stopping stream…", live: "Live now", offAir: "Not live", started: "Started", conversions: "Attributed conversions", noConversions: "No conversions for this session yet.", sandbox: "Sandbox paid", unavailable: "Studio is unavailable. Try again.", auth: "Studio access is not available for this account.", lastSession: "Last session", noSession: "Start a live session to see attributed conversions.", reload: "Refresh Studio", source: "Source" }, fr: { eyebrow: "VENDRE / STUDIO DIRECT", title: "Studio en direct", preview: "Les commandes de direct nécessitent l’application de bureau Yaatal.", locked: "Connectez-vous pour préparer votre session Studio.", loading: "Récupération de votre session Studio…", retry: "Réessayer", readiness: "État du Studio", queue: "File de produits", noProducts: "Aucun produit n’est dans la file de ce direct.", openShop: "Ouvrir dans SHOP", share: "Partager", start: "Lancer le direct", starting: "Lancement du direct…", stop: "Arrêter le direct", stopping: "Arrêt du direct…", live: "En direct", offAir: "Hors direct", started: "Démarré", conversions: "Conversions attribuées", noConversions: "Aucune conversion pour cette session.", sandbox: "Paiement test", unavailable: "Le Studio est indisponible. Réessayez.", auth: "L’accès au Studio n’est pas disponible pour ce compte.", lastSession: "Dernière session", noSession: "Lancez un direct pour voir les conversions attribuées.", reload: "Actualiser le Studio", source: "Source" } } as const;
const surfaceMessages = {
  en: { stageLabel: "Live product preview", imageUnavailable: "Product image unavailable", activity: "Live assistant", noActivity: "No Studio activity is available yet.", integrity: "Session integrity", ledgerAvailable: "The Studio ledger is available for this session.", ledgerUnknown: "Ledger availability has not been confirmed.", productsReady: "Products ready to present", commerce: "COMMERCE", voiceUnavailable: "Voice control unavailable", voiceDetail: "Microphone authority is not connected to this session.", studioFallback: "Studio", inStock: "In stock", lowStock: "Low stock", outOfStock: "Out of stock" },
  fr: { stageLabel: "Aperçu produit en direct", imageUnavailable: "Image du produit indisponible", activity: "Assistant en direct", noActivity: "Aucune activité Studio n’est encore disponible.", integrity: "Intégrité de session", ledgerAvailable: "Le registre Studio est disponible pour cette session.", ledgerUnknown: "La disponibilité du registre n’est pas confirmée.", productsReady: "Produits prêts à présenter", commerce: "COMMERCE", voiceUnavailable: "Commande vocale indisponible", voiceDetail: "L’autorité du microphone n’est pas connectée à cette session.", studioFallback: "Studio", inStock: "En stock", lowStock: "Stock limité", outOfStock: "Rupture de stock" },
} as const;
function errorText(error: unknown, fallback: string) { return error instanceof Error && error.message ? error.message : fallback; }
function dedupe(values: Conversion[]) { const seen = new Set<string>(); return values.filter(value => !seen.has(value.orderId) && (seen.add(value.orderId), true)); }
function elapsed(startedAt: number, now: number) { const seconds = Math.max(0, Math.floor((now - startedAt * 1_000) / 1_000)); return [Math.floor(seconds / 3_600), Math.floor(seconds / 60) % 60, seconds % 60].map(value => String(value).padStart(2, "0")).join(":"); }
function stockLabel(status: string, copy: { inStock: string; lowStock: string; outOfStock: string }) { if (status === "in_stock") return copy.inStock; if (status === "low_stock") return copy.lowStock; if (status === "out_of_stock") return copy.outOfStock; return status; }
function StageMedia({ source, alt, unavailable }: { source?: string; alt: string; unavailable: string }) { const [failed, setFailed] = useState(false); useEffect(() => setFailed(false), [source]); return source && !failed ? <img className="sell-stage-image" src={source} alt={alt} onError={() => setFailed(true)} /> : <div className="sell-stage-empty" role="img" aria-label={unavailable}><ImageOff aria-hidden="true" size={30} /></div>; }
function ProductThumbnail({ source, unavailable }: { source?: string; unavailable: string }) { const [failed, setFailed] = useState(false); useEffect(() => setFailed(false), [source]); return <span className="sell-product-image" role={!source || failed ? "img" : undefined} aria-label={!source || failed ? unavailable : undefined}>{source && !failed ? <img src={source} alt="" onError={() => setFailed(true)} /> : <ImageOff aria-hidden="true" size={22} />}</span>; }

/** Shell wiring supplies the authenticated adapter and callbacks. Native events are invalidation-only; this component never polls. */
export function SellWorkspace({ adapter, authenticated, accountEpoch = 0, recoveryEpoch = 0, studioResetEpoch = 0, studioReady = true, conversionInvalidation = null, mode, selectedProductId, onSelectProduct, onOpenShop, onShare: sendShare, onSessionChange, locale = "en" }: SellWorkspaceProps) {
  const copy = messages[locale]; const surface = surfaceMessages[locale]; const localeRef = useRef(locale); localeRef.current = locale; const [phase, setPhase] = useState<Phase>("loading"); const [session, setSession] = useState<StudioSessionState | null>(null); const [status, setStatus] = useState<StudioStatus | null>(null); const [queue, setQueue] = useState<ProductQueue | null>(null); const [retainedSessionId, setRetainedSessionId] = useState<string | null>(null); const [conversions, setConversions] = useState<Conversion[]>([]); const [conversionState, setConversionState] = useState<"idle" | "loading" | "ready" | "error">("idle"); const [error, setError] = useState(""); const [conversionError, setConversionError] = useState(""); const [operation, setOperation] = useState<Operation>(null); const [now, setNow] = useState(Date.now()); const [conversionRefresh, setConversionRefresh] = useState(0); const request = useRef(0); const conversionRequest = useRef(0); const epochs = useRef({ account: accountEpoch, studio: studioResetEpoch });
  const clear = useCallback((next: Phase) => { setPhase(next); setSession(null); setStatus(null); setQueue(null); setRetainedSessionId(null); setConversions([]); setError(""); setOperation(null); }, []);
  const hydrate = useCallback(async () => { const version = ++request.current; setPhase("loading"); setError(""); try { const bootstrap = await adapter.bootstrap(); if (version !== request.current) return; if (!bootstrap.authenticated) { setPhase("locked"); setError(messages[localeRef.current].auth); return; } const [nextSession, nextStatus, nextQueue] = await Promise.all([adapter.sessionState(), adapter.status(), adapter.productQueue()]); if (version !== request.current) return; setSession(nextSession); setStatus(nextStatus); setQueue(nextQueue); setRetainedSessionId(current => nextSession.sessionId || current); setPhase("ready"); } catch (failure) { if (version === request.current) { setPhase("error"); setError(errorText(failure, messages[localeRef.current].unavailable)); } } }, [adapter]);
  useEffect(() => { request.current += 1; const accountChanged = epochs.current.account !== accountEpoch; const studioReset = epochs.current.studio !== studioResetEpoch; epochs.current = { account: accountEpoch, studio: studioResetEpoch }; if (mode === "preview") { clear("preview"); return; } if (!authenticated) { clear("locked"); return; } if (accountChanged || studioReset) clear("loading"); if (studioResetEpoch > 0 && !studioReady) return; void hydrate(); return () => { request.current += 1; conversionRequest.current += 1; }; }, [accountEpoch, authenticated, clear, hydrate, mode, recoveryEpoch, studioReady, studioResetEpoch]);
  const scope = session?.sessionId || retainedSessionId;
  const conversionEventEpoch = conversionInvalidation?.liveSessionId === scope ? conversionInvalidation.epoch : 0;
  useEffect(() => { if (!scope || phase !== "ready") { conversionRequest.current += 1; setConversions([]); setConversionState("idle"); setConversionError(""); return; } const version = ++conversionRequest.current; setConversionState("loading"); setConversionError(""); void adapter.conversions(scope).then(values => { if (version === conversionRequest.current) { setConversions(dedupe(values)); setConversionState("ready"); } }).catch(failure => { if (version === conversionRequest.current) { setConversions([]); setConversionState("error"); setConversionError(errorText(failure, messages[localeRef.current].unavailable)); } }); return () => { conversionRequest.current += 1; }; }, [adapter, conversionEventEpoch, conversionRefresh, phase, scope]);
  useEffect(() => { onSessionChange?.(phase === "ready" ? session : null); }, [onSessionChange, phase, session]);
  useEffect(() => { if (!session?.isLive || !session.startedAt) return; const timer = window.setInterval(() => setNow(Date.now()), 1_000); return () => window.clearInterval(timer); }, [session?.isLive, session?.startedAt]);
  const control = useCallback(async (action: Exclude<Operation, null>) => { if (operation || phase !== "ready") return; const version = request.current; const currentScope = session?.sessionId || retainedSessionId; setOperation(action); setError(""); try { const next = action === "start" ? await adapter.goLive() : await adapter.stopStream(); if (version === request.current) { setSession(next); setRetainedSessionId(next.sessionId || currentScope || null); } } catch (failure) { if (version === request.current) setError(errorText(failure, copy.unavailable)); } finally { if (version === request.current) setOperation(null); } }, [adapter, copy.unavailable, operation, phase, retainedSessionId, session?.sessionId]);
  const onShare = useCallback((productId: string) => { const product = queue?.products.find(item => item.id === productId); if (authenticated && session?.isLive && product && product.stock > 0 && !/out[ -]?of[ -]?stock|sold[ -]?out|unavailable/i.test(product.stockStatus)) sendShare(productId); }, [authenticated, queue?.products, sendShare, session?.isLive]);
  const clock = useMemo(() => session?.isLive && session.startedAt ? elapsed(session.startedAt, now) : copy.offAir, [copy.offAir, now, session]);
  if (phase !== "ready") return <section className="sell-workspace sell-workspace--state" aria-labelledby="sell-heading"><p className="eyebrow">{copy.eyebrow}</p><h1 id="sell-heading">{copy.title}</h1><div className="sell-state" role={phase === "error" ? "alert" : "status"}>{phase === "loading" && <LoaderCircle className="sell-spinner" aria-hidden="true" size={20} />}<p>{phase === "preview" ? copy.preview : phase === "locked" ? error || copy.locked : phase === "loading" ? copy.loading : error}</p>{phase === "error" && <Button onClick={() => void hydrate()}><RefreshCw size={18} />{copy.retry}</Button>}</div></section>;
  const shareAvailable = (product: { stock: number; stockStatus: string }) => authenticated && Boolean(session?.isLive) && product.stock > 0 && !/out[ -]?of[ -]?stock|sold[ -]?out|unavailable/i.test(product.stockStatus);
  const conversionContent = !scope ? <p className="sell-empty">{copy.noSession}</p> : conversionState === "loading" ? <p className="sell-empty" role="status"><LoaderCircle className="sell-spinner" aria-hidden="true" size={18} />{copy.loading}</p> : conversionState === "error" ? <div className="sell-conversion-error" role="alert"><p>{conversionError}</p><Button variant="outline" onClick={() => setConversionRefresh(value => value + 1)}>{copy.retry}</Button></div> : conversions.length ? <ul>{conversions.map(conversion => <li key={conversion.orderId}><div><strong>{conversion.productName}</strong><span>{conversion.orderId} · {conversion.sourceChannel}</span></div><div><strong>{conversion.totalFcfa.toLocaleString(locale === "fr" ? "fr-SN" : "en-SN")} FCFA</strong><span>{conversion.paymentProvider} · {copy.sandbox}</span></div></li>)}</ul> : <p className="sell-empty">{copy.noConversions}</p>;
  const featured = queue?.products.find(product => product.id === selectedProductId) || queue?.products[0];
  const featuredImage = featured?.images.find(image => image.trim());
  return <section className="sell-workspace" aria-labelledby="sell-heading">
    <header className="sell-heading"><div><p className="eyebrow">{copy.eyebrow}</p><div className="sell-title-row"><h1 id="sell-heading">{copy.title}</h1><div className={`sell-live-status ${session?.isLive ? "is-live" : ""}`} role="status"><i aria-hidden="true" />{session?.isLive ? copy.live : copy.offAir}</div></div></div><Button className="sell-shop-launch" variant="outline" onClick={() => { if (featured) onSelectProduct(featured.id); onOpenShop(); }}>{copy.openShop}<ArrowRight aria-hidden="true" size={18} /></Button></header>
    {error && <p className="sell-error" role="alert">{error}</p>}
    <div className="sell-layout">
      <section className="sell-stage" aria-label={surface.stageLabel}>
        <StageMedia source={featuredImage} alt={featured?.name || ""} unavailable={surface.imageUnavailable} />
        <div className="sell-stage-scrim" aria-hidden="true" />
        <div className="sell-stage-topline"><span>{featured?.category || surface.stageLabel}</span><span className="sell-stage-timer">{session?.isLive && <i aria-hidden="true" />}{clock}</span></div>
        <div className="sell-stage-caption"><span className={session?.isLive ? "sell-on-air is-live" : "sell-on-air"}>{session?.isLive ? copy.live : copy.offAir}</span><strong>{featured?.name || copy.noProducts}</strong>{featured && <span>{featured.priceDisplay}</span>}</div>
      </section>
      <aside className="sell-activity" aria-label={surface.activity}>
        <div className="sell-section-heading"><div><p className="eyebrow">{copy.readiness}</p><h2>{surface.activity}</h2></div><span>{status?.readiness.status || "—"}</span></div>
        <ol>{status?.readiness.steps.length ? status.readiness.steps.map(step => <li key={step.name}><strong>{step.name}</strong><span><b data-status={step.status}>{step.status}</b>{step.durationMs !== undefined ? ` · ${step.durationMs} ms` : ""}</span></li>) : <li className="sell-empty">{surface.noActivity}</li>}</ol>
        <div className="sell-governance"><ShieldCheck aria-hidden="true" size={22} /><div><strong>{surface.integrity}</strong><p>{status?.ledgerAvailable ? surface.ledgerAvailable : surface.ledgerUnknown}</p></div></div>
      </aside>
      <section className="sell-products"><div className="sell-section-heading"><div><p className="eyebrow">{copy.queue}</p><h2>{surface.productsReady}</h2></div>{queue && <span>{copy.source}: {queue.source}</span>}</div>{queue?.products.length ? <ul className="sell-product-strip">{queue.products.map(product => { const image = product.images.find(value => value.trim()); return <li key={product.id} className={`sell-product ${selectedProductId === product.id ? "is-selected" : ""}`}><button type="button" onClick={() => onSelectProduct(product.id)} aria-label={`${product.name} ${product.priceDisplay}`} aria-pressed={selectedProductId === product.id}><ProductThumbnail source={image} unavailable={surface.imageUnavailable} /><span className="sell-product-copy"><strong>{product.name}</strong><span>{product.priceDisplay}</span><em>{stockLabel(product.stockStatus, surface)}</em></span></button><div><Button variant="ghost" aria-label={copy.openShop} onClick={() => { onSelectProduct(product.id); onOpenShop(); }}><ShoppingBag aria-hidden="true" size={16} /></Button><Button variant="ghost" aria-label={copy.share} disabled={!shareAvailable(product)} onClick={() => onShare(product.id)}><Share2 aria-hidden="true" size={16} /></Button></div></li>; })}</ul> : <p className="sell-empty">{copy.noProducts}</p>}</section>
    </div>
    <footer className="sell-voice-dock"><span className="sell-mic"><MicOff aria-hidden="true" size={19} /></span><div><strong>{surface.voiceUnavailable}</strong><span>{surface.voiceDetail}</span></div><span className="sell-voice-hint"><span className="sell-seller-name">{session?.sellerName || surface.studioFallback}</span> · {copy.started}: {session?.startedAt ? new Date(session.startedAt * 1_000).toLocaleTimeString(locale === "fr" ? "fr-SN" : "en-SN", { hour: "numeric", minute: "2-digit" }) : "—"}</span><div className="sell-live-actions">{session?.isLive ? <Button disabled={operation !== null} onClick={() => void control("stop")}><CircleStop size={18} />{operation === "stop" ? copy.stopping : copy.stop}</Button> : <Button disabled={operation !== null} onClick={() => void control("start")}><Radio size={18} />{operation === "start" ? copy.starting : copy.start}</Button>}<Button variant="outline" aria-label={copy.reload} disabled={operation !== null} onClick={() => void hydrate()}><RefreshCw size={18} /></Button></div></footer>
    <section className="sell-conversions"><div className="sell-section-heading"><div><p className="eyebrow">{surface.commerce}</p><h2>{copy.conversions}</h2></div>{scope && <span>{session?.isLive ? copy.live : copy.lastSession}</span>}</div>{conversionContent}</section>
  </section>;
}
