import { useEffect, useRef, useState } from "react";
import { Copy, ExternalLink, LoaderCircle, Send } from "lucide-react";
import type { CatalogProduct, CommerceChannel, CommerceIntent, CommerceWorkspaceAdapter } from "../../contracts";
import { Button } from "../../components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "../../components/ui/dialog";

export function ShareDialog({ adapter, productId, accountEpoch = 0, open, onOpenChange, locale = "en" }: { adapter: CommerceWorkspaceAdapter; productId: string | null; accountEpoch?: number; open: boolean; onOpenChange(open: boolean): void; locale?: "en" | "fr" }) {
  const fr = locale === "fr"; const [product, setProduct] = useState<CatalogProduct | null>(null); const [intent, setIntent] = useState<CommerceIntent | null>(null); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const version = useRef(0); const identity = useRef("");
  identity.current = `${accountEpoch}:${open}:${productId || ""}`;
  const isCurrent = (request: number, target: string) => request === version.current && target === identity.current;
  useEffect(() => { const current = ++version.current; const target = `${accountEpoch}:${open}:${productId || ""}`; setProduct(null); setIntent(null); setError(""); setNotice(""); if (!open || !productId) return; setPending(true); void adapter.catalog.product(productId).then(value => { if (isCurrent(current, target)) setProduct(value); }).catch(() => { if (isCurrent(current, target)) setError(fr ? "Ce produit n’est pas disponible." : "This product is unavailable."); }).finally(() => { if (isCurrent(current, target)) setPending(false); }); return () => { version.current += 1; }; }, [accountEpoch, adapter, fr, open, productId]);
  async function create() { if (!productId || pending) return; const current = ++version.current; const target = `${accountEpoch}:${open}:${productId}`; setPending(true); setError(""); setNotice(""); try { const next = await adapter.createIntent(productId); if (isCurrent(current, target)) { setIntent(next); setNotice(fr ? "Liens prêts à être partagés." : "Links are ready to share."); } } catch { if (isCurrent(current, target)) setError(fr ? "Impossible de créer un lien de vente." : "We could not create a commerce link."); } finally { if (isCurrent(current, target)) setPending(false); } }
  async function openChannel(channel: CommerceChannel) { if (!intent || pending) return; const current = ++version.current; const target = `${accountEpoch}:${open}:${productId || ""}`; setPending(true); setError(""); setNotice(""); try { const result = await adapter.openLink(intent.intentId, channel); if (!isCurrent(current, target)) return; if (channel === "copy") { if (!navigator.clipboard?.writeText) throw new Error("clipboard unavailable"); await navigator.clipboard.writeText(result.publicUrl); if (isCurrent(current, target)) setNotice(fr ? "Lien copié." : "Link copied."); } else if (result.opened) setNotice(fr ? "Lien ouvert." : "Link opened."); else setError(fr ? "L’application de bureau n’a pas ouvert ce lien." : "The desktop app did not open this link."); } catch { if (isCurrent(current, target)) setError(channel === "copy" ? (fr ? "Impossible de copier ce lien." : "We could not copy this link.") : (fr ? "Impossible d’ouvrir ce lien." : "We could not open this link.")); } finally { if (isCurrent(current, target)) setPending(false); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><p className="eyebrow">{fr ? "PARTAGER" : "SHARE"}</p><DialogTitle>{product?.name || (fr ? "Préparer le lien" : "Prepare your link")}</DialogTitle><DialogDescription>{product ? `${product.priceDisplay} · ${product.stock} ${fr ? "en stock" : "in stock"}` : fr ? "Les détails du produit sont vérifiés avant de créer un lien." : "Product details are verified before a link is created."}</DialogDescription>{pending && <p role="status"><LoaderCircle aria-hidden="true" size={18} /> {fr ? "Préparation…" : "Preparing…"}</p>}{error && <p className="notice error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{!intent && product && <Button disabled={pending || product.stock <= 0} onClick={() => void create()}><ExternalLink size={18} />{fr ? "Créer le lien" : "Create link"}</Button>}{intent && <div className="commerce-actions"><Button disabled={pending} onClick={() => void openChannel("copy")}><Copy size={18} />{fr ? "Copier" : "Copy"}</Button><Button variant="outline" disabled={pending} onClick={() => void openChannel("livestream")}><ExternalLink size={18} />{fr ? "Direct" : "Livestream"}</Button><Button variant="outline" disabled={pending} onClick={() => void openChannel("telegram")}><Send size={18} />Telegram</Button><Button variant="outline" disabled={pending} onClick={() => void openChannel("whatsapp")}><Send size={18} />WhatsApp</Button></div>}</DialogContent></Dialog>;
}
