"""
Yaatal NFC Delivery — delivery confirmation for the Yaatal Engine.

When a customer receives a product, they tap the NFC card/sticker
included in the package with their phone. This opens a URL that
confirms delivery to the Yaatal Engine, which:
  1. Marks the order as delivered
  2. Triggers any post-delivery flows (reviews, re-order prompts, etc.)
  3. Releases payment to the merchant if escrowed

This is NOT a product page or checkout — the Engine handles all commerce.
This module is solely the delivery confirmation bridge: NFC tap → Engine API.

NFC URL format (written to the tag, NDEF URI record):
  https://yaatal.shop/d/{delivery_code}

The {delivery_code} is a unique, one-time-use code generated by the Engine
when the order is shipped. It maps to a specific order + customer.
The tag is physically included in the package by the merchant/fulfillment.

Hybrid flow:
  Merchant proposes: packs order, includes NFC tag with delivery code
  Model executes: customer taps NFC on delivery → this module receives tap
  Engine disposes: confirms delivery, closes order, releases payment
"""

import json
import logging
import os
import time
from dataclasses import dataclass
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

# ─── Config ────────────────────────────────────────────────────────────
ENGINE_API_URL = os.getenv("ENGINE_API_URL", "http://yaatal-engine:8080").rstrip("/")
ENGINE_CHECKOUT_BASE = os.getenv("ENGINE_CHECKOUT_BASE", "https://engine.njooba.com").rstrip("/")


@dataclass
class DeliveryConfirmation:
    """A delivery confirmation event from an NFC tap."""
    delivery_code: str  # Unique code from the NFC tag
    order_id: str = ""  # Resolved from the Engine
    customer_id: str = ""  # Resolved from the Engine
    merchant_id: str = ""  # Resolved from the Engine
    confirmed_at: float = 0.0
    location_lat: Optional[float] = None  # If phone provides GPS
    location_lon: Optional[float] = None
    device_info: str = ""  # User agent / device


class DeliveryBridge:
    """Bridges NFC delivery taps to the Yaatal Engine API.

    When a customer taps the NFC tag, their phone opens a URL:
        https://yaatal.shop/d/{delivery_code}

    The Engine serves this URL and handles the confirmation page.
    This module provides:
      1. URL generation for programming NFC tags with delivery codes
      2. An API client for sending confirmations to the Engine
      3. A lightweight confirmation page server (optional — the Engine
         can serve the page directly, this is for standalone deployment)

    `confirm_delivery` is wired to the Engine's real anonymous endpoint
    (`POST /api/deliveries/confirm-by-code`); status-by-code remains a stub
    (no JSON endpoint Engine-side yet).
    """

    def __init__(self, engine_api_url: str = ENGINE_API_URL,
                 engine_checkout_base: str = ENGINE_CHECKOUT_BASE,
                 engine_api_key: str = ""):
        """
        Args:
            engine_api_url: Yaatal Engine API base URL (e.g. http://yaatal-engine:8080)
            engine_checkout_base: Engine public-facing checkout base (e.g. https://engine.njooba.com)
            engine_api_key: API key for Engine authentication (if needed)
        """
        self.engine_api_url = engine_api_url.rstrip("/")
        self.engine_checkout_base = engine_checkout_base.rstrip("/")
        self.engine_api_key = engine_api_key

    # ─── NFC URL generation (for programming tags) ──────────────────

    def generate_delivery_url(self, delivery_code: str) -> str:
        """Generate the URL to write to an NFC tag for a delivery.

        This URL is written to the NTAG215 sticker that goes in the package.
        When the customer taps it on delivery, their phone opens this URL.

        Args:
            delivery_code: Unique delivery code from the Engine

        Returns:
            URL string (e.g. https://yaatal.shop/d/ABC123XYZ)
        """
        return f"{self.engine_checkout_base}/d/{delivery_code}"

    def generate_delivery_urls(self, delivery_codes: list[str]) -> dict[str, str]:
        """Generate NFC URLs for multiple delivery codes (batch).

        Used by merchants/fulfillment to program a batch of NFC tags
        before shipping.

        Args:
            delivery_codes: List of delivery codes from the Engine

        Returns:
            Dict of delivery_code → URL
        """
        return {
            code: self.generate_delivery_url(code)
            for code in delivery_codes
        }

    # ─── Engine API client ───────────────────────────────────────────

    async def confirm_delivery(self, delivery_code: str,
                               location_lat: Optional[float] = None,
                               location_lon: Optional[float] = None,
                               device_info: str = "",
                               order_id: str = "") -> dict:
        """Send a delivery confirmation to the Yaatal Engine.

        Calls the Engine's anonymous one-time-code endpoint
        (`POST /api/deliveries/confirm-by-code`). The Engine validates the
        code, marks the order delivered, releases escrowed payment for
        BOBO-linked orders, and permanently burns the code.

        Args:
            delivery_code: The code from the NFC tag
            location_lat: Optional GPS latitude (currently unused by Engine)
            location_lon: Optional GPS longitude (currently unused by Engine)
            device_info: Optional device info (currently unused by Engine)
            order_id: Optional order ID (Engine resolves from code)

        Returns:
            dict — on success: {"status": "confirmed", "delivery_id", "order_id",
            "payment_released"}; on failure: {"status": "error", "http_status",
            "message"} (400 = code already used, 404 = unknown code).
        """
        url = f"{self.engine_api_url}/api/deliveries/confirm-by-code"
        payload = {"delivery_code": delivery_code}
        if order_id:
            payload["order_id"] = order_id

        headers = {"Content-Type": "application/json"}
        if self.engine_api_key:
            headers["Authorization"] = f"Bearer {self.engine_api_key}"

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(url, json=payload, headers=headers)
                if resp.status_code == 200:
                    result = resp.json()
                    logger.info("Delivery confirmed: code=%s order=%s released=%s",
                                delivery_code, result.get("order_id"),
                                result.get("payment_released"))
                    return result
                else:
                    logger.warning("Delivery confirmation rejected (%s): code=%s",
                                   resp.status_code, delivery_code)
                    return {
                        "status": "error",
                        "http_status": resp.status_code,
                        "message": resp.text or "Confirmation rejected",
                    }
        except httpx.ConnectError as e:
            logger.error("Engine unreachable for confirmation: %s", e)
            return {"status": "engine_unreachable", "http_status": 0,
                    "message": "Engine service unavailable"}
        except (httpx.TimeoutException, Exception) as e:
            logger.error("Engine request failed: %s", e)
            return {"status": "error", "http_status": 0,
                    "message": str(e)}

    def get_delivery_status(self, delivery_code: str) -> dict:
        """Check the delivery status of a code from the Engine.

        Args:
            delivery_code: The delivery code

        Returns:
            Engine response with order info + delivery status
        """
        # ponytail: still a stub — the Engine serves GET /d/{code} as an HTML
        # page but exposes no JSON status-by-code endpoint yet. Upgrade path:
        # Engine GET /api/deliveries/status-by-code/{code} if a machine-readable
        # status check is ever actually needed (the confirm call already
        # returns the outcome).
        logger.info("Delivery status check (stub): code=%s", delivery_code)
        return {
            "status": "stub",
            "delivery_code": delivery_code,
            "message": "Engine exposes no JSON status-by-code endpoint yet",
        }

    def invalidate_code(self, delivery_code: str) -> dict:
        """Deprecated: the Engine burns codes server-side on confirmation.

        One-time use is enforced by the Engine (`code_used_at`); a used code
        can never confirm again. There is nothing for the client to invalidate.
        """
        logger.info("invalidate_code is a no-op — Engine enforces one-time use "
                    "server-side (code=%s)", delivery_code)
        return {"status": "noop",
                "message": "Engine enforces one-time use server-side"}


# ─── Optional standalone confirmation page server ───────────────────

def _error_page(title: str, message: str) -> str:
    """Generate a mobile-first error page for delivery failures."""
    return f"""<!DOCTYPE html>
<html lang="wo">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — Yaatal</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, 'Segoe UI', Arial, sans-serif;
            background: #f5f5f5; color: #1a1a1a;
            padding: 20px; max-width: 500px; margin: 0 auto;
        }}
        .error-card {{
            background: white; border-radius: 16px;
            padding: 32px 24px; text-align: center;
            box-shadow: 0 2px 12px rgba(0,0,0,0.1); margin-top: 40px;
        }}
        .error-icon {{
            width: 80px; height: 80px; border-radius: 50%;
            background: #f44336; margin: 0 auto 20px;
            display: flex; align-items: center; justify-content: center;
            font-size: 40px; color: white;
        }}
        .error-title {{ font-size: 22px; font-weight: 700; margin-bottom: 8px; }}
        .error-subtitle {{ font-size: 14px; color: #666; margin-bottom: 16px; line-height: 1.4; }}
    </style>
</head>
<body>
    <div class="error-card">
        <div class="error-icon">✕</div>
        <div class="error-title">{title}</div>
        <div class="error-subtitle">{message}</div>
    </div>
</body>
</html>"""


def create_delivery_server(bridge: Optional[DeliveryBridge] = None):
    """Create a lightweight FastAPI server for delivery confirmation pages.

    This is OPTIONAL — the Yaatal Engine can serve the /d/{code} page
    directly. This standalone server is for testing or for deployment
    where the Engine isn't serving the confirmation page yet.

    Routes:
      GET  /d/{delivery_code}  — Confirmation page (mobile-first HTML)
      POST /api/delivery/confirm — API endpoint for confirmations
      GET  /api/delivery/{code}  — API status check

    Run from the repo root:
      uvicorn --factory live.nfc_delivery.server:app_factory
    """
    from fastapi import FastAPI, HTTPException, Request
    from fastapi.responses import HTMLResponse, JSONResponse

    if bridge is None:
        bridge = DeliveryBridge()

    app = FastAPI(title="Yaatal Delivery Confirmation", version="0.2.0")

    @app.get("/d/{delivery_code}", response_class=HTMLResponse)
    async def delivery_page(delivery_code: str, request: Request):
        """Mobile-first delivery confirmation page.

        Customer taps NFC tag → phone opens this page → confirms delivery.
        The page shows order info (from Engine) and a confirm button.
        If Engine is unreachable, shows a service-unavailable error page.
        """
        # Get delivery info from Engine (stub for now — no JSON endpoint)
        info = bridge.get_delivery_status(delivery_code)

        # Extract device/location if available
        device_info = request.headers.get("user-agent", "")
        client_host = request.client.host if request.client else ""

        return f"""<!DOCTYPE html>
<html lang="wo">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Livraison confirmée — Yaatal</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, 'Segoe UI', Arial, sans-serif;
            background: #f5f5f5; color: #1a1a1a;
            padding: 20px; max-width: 500px; margin: 0 auto;
        }}
        .confirm-card {{
            background: white; border-radius: 16px;
            padding: 32px 24px; text-align: center;
            box-shadow: 0 2px 12px rgba(0,0,0,0.1); margin-top: 40px;
        }}
        .check-icon {{
            width: 80px; height: 80px; border-radius: 50%;
            background: #4CAF50; margin: 0 auto 20px;
            display: flex; align-items: center; justify-content: center;
            font-size: 40px; color: white;
        }}
        .confirm-title {{
            font-size: 22px; font-weight: 700; margin-bottom: 8px;
        }}
        .confirm-subtitle {{
            font-size: 14px; color: #666; margin-bottom: 24px; line-height: 1.4;
        }}
        .order-info {{
            background: #f9f9f9; border-radius: 8px; padding: 16px;
            margin-bottom: 24px; text-align: left; font-size: 14px;
        }}
        .order-info div {{ margin-bottom: 6px; }}
        .order-info .label {{ color: #999; font-size: 12px; }}
        .confirm-btn {{
            background: #4CAF50; color: white; border: none;
            padding: 16px 32px; border-radius: 12px;
            font-size: 16px; font-weight: 600; width: 100%;
            cursor: pointer; transition: transform 0.1s;
        }}
        .confirm-btn:active {{ transform: scale(0.98); }}
        .confirm-btn:disabled {{ background: #ccc; }}
        .confirmed-msg {{
            display: none; color: #4CAF50; font-weight: 600;
            margin-top: 16px; font-size: 18px;
        }}
        .error-msg {{
            display: none; color: #f44336; font-weight: 600;
            margin-top: 16px; font-size: 15px;
        }}
    </style>
</head>
<body>
    <div class="confirm-card">
        <div class="check-icon">✓</div>
        <div class="confirm-title">Colis reçu ?</div>
        <div class="confirm-subtitle">
            Vous avez reçu votre commande. Confirmez la livraison<br>
            <small>Térëleg bi nak yég ngéen ko? Dëggalal lees</small>
        </div>
        <div class="order-info">
            <div><span class="label">Code de livraison:</span> {delivery_code}</div>
            <div><span class="label">Statut:</span> {info.get('status', 'pending')}</div>
        </div>
        <button class="confirm-btn" onclick="confirmDelivery()"
                id="confirmBtn">
            📦 Confirmer la livraison
        </button>
        <div class="confirmed-msg" id="confirmedMsg">
            ✓ Livraison confirmée. Merci !
        </div>
        <div class="error-msg" id="errorMsg"></div>
    </div>
    <script>
        async function confirmDelivery() {{
            const btn = document.getElementById('confirmBtn');
            btn.disabled = true;
            btn.textContent = 'Confirmation...';
            const errEl = document.getElementById('errorMsg');
            errEl.style.display = 'none';
            try {{
                const resp = await fetch('/api/delivery/confirm', {{
                    method: 'POST',
                    headers: {{'Content-Type': 'application/json'}},
                    body: JSON.stringify({{
                        delivery_code: '{delivery_code}',
                        device_info: navigator.userAgent,
                    }}),
                }});
                const data = await resp.json();
                if (data.status === 'confirmed') {{
                    btn.style.display = 'none';
                    document.getElementById('confirmedMsg').style.display = 'block';
                }} else if (data.status === 'engine_unreachable') {{
                    btn.disabled = false;
                    btn.textContent = 'Réessayer';
                    errEl.textContent = 'Service indisponible. Réessayez plus tard.';
                    errEl.style.display = 'block';
                }} else {{
                    btn.disabled = false;
                    btn.textContent = 'Réessayer';
                    errEl.textContent = data.message || 'Erreur de confirmation';
                    errEl.style.display = 'block';
                }}
            }} catch(e) {{
                btn.disabled = false;
                btn.textContent = 'Réessayer';
                errEl.textContent = 'Connexion échouée. Réessayez.';
                errEl.style.display = 'block';
            }}
        }}
    </script>
</body>
</html>"""

    @app.get("/d/{delivery_code}/error", response_class=HTMLResponse)
    async def delivery_error_page(delivery_code: str):
        """Service-unavailable fallback page when Engine is down."""
        return _error_page(
            "Service indisponible",
            "Le service de confirmation est temporairement indisponible. "
            "Veuillez réessayer plus tard."
        )

    @app.post("/api/delivery/confirm")
    async def confirm_api(request: Request):
        """API endpoint for delivery confirmation.

        Posts to Engine POST /api/deliveries/confirm-by-code.
        Returns Engine response or error if Engine unreachable.
        """
        body = await request.json()
        delivery_code = body.get("delivery_code", "")
        device_info = body.get("device_info", "")
        order_id = body.get("order_id", "")
        result = await bridge.confirm_delivery(
            delivery_code=delivery_code,
            device_info=device_info,
            order_id=order_id,
        )
        return JSONResponse(result)

    @app.get("/api/delivery/{delivery_code}")
    async def status_api(delivery_code: str):
        """API endpoint for delivery status check."""
        return bridge.get_delivery_status(delivery_code)

    return app


def app_factory():
    """Uvicorn factory: `uvicorn --factory live.nfc_delivery.server:app_factory`."""
    return create_delivery_server(DeliveryBridge())