import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ImageOff, LoaderCircle, PackageCheck, ShieldCheck, ShoppingBag, Truck } from "lucide-react";
import type { CatalogPage, CatalogProduct } from "../../contracts";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import "./ShopWorkspace.css";

export interface ShopWorkspaceProps {
  catalog: { list(args?: { page?: number; category?: string }): Promise<CatalogPage>; product(productId: string): Promise<CatalogProduct>; };
  authenticated?: boolean; accountEpoch?: number; selectedProductId: string | null; onSelectProduct(id: string): void;
  onReturnToLive(): void; onShare(productId: string): void; canShare: boolean; mode: "native" | "preview"; locale?: "en" | "fr";
}

const messages = {
  en: {
    eyebrow: "SHOP / CATALOG", title: "Products for your next live.", preview: "Catalog browsing is unavailable in browser preview. Open the Yaatal desktop app to use your live catalog.",
    search: "Search loaded products", placeholder: "Search products already loaded", category: "Category", all: "All loaded categories",
    scope: (shown: number, loaded: number) => `Showing ${shown} of ${loaded} loaded products. Search only checks products already loaded.`, loading: "Loading products…", retry: "Retry", more: (count: number) => `Load ${count} more`, loadingMore: "Loading more…", none: "No products are available in this category.", matches: "No loaded products match this search.", select: "Select a product to view its current catalog details.", open: (name: string) => `Open ${name}`, image: "Product image unavailable", out: "Out of stock", in: "In stock", detailLoading: "Loading current product details…", unavailable: "This product is no longer available in the catalog.", problem: "We could not load this product. Try again.", back: "Return to Live", variants: "Available options", description: "Description", noDescription: "No product description is available.",
    selectedProduct: "Selected product", seller: "Seller", sellerUnavailable: "Seller details are not available in this catalog record.", delivery: "Delivery", deliveryBody: "Delivery availability is confirmed in the configured commerce flow.", governance: "Governance", governanceBody: "Availability and payment remain authoritative in Engine.", commerceSheet: "COMMERCE SHEET", commerceTitle: "Ready for commerce", commerceBody: "This product remains linked to the current Engine commerce flow.", catalogPrice: "Catalog price", availability: "Availability", openCommerce: "Open Commerce Sheet", shareSignedOut: "Sign in to open Commerce Sheet.", shareNoLive: "Start a live session to create a commerce link.", shareOutOfStock: "This product is out of stock and cannot be shared.", imagePicker: (name: string) => `${name} images`, viewImage: (index: number) => `View image ${index}`,
  },
  fr: {
    eyebrow: "BOUTIQUE / CATALOGUE", title: "Des produits pour votre prochain direct.", preview: "La consultation du catalogue n’est pas disponible dans l’aperçu navigateur. Ouvrez l’application de bureau Yaatal pour utiliser votre catalogue live.",
    search: "Rechercher parmi les produits chargés", placeholder: "Rechercher les produits déjà chargés", category: "Catégorie", all: "Toutes les catégories chargées",
    scope: (shown: number, loaded: number) => `${shown} produit${shown === 1 ? "" : "s"} affiché${shown === 1 ? "" : "s"} sur ${loaded} chargé${loaded === 1 ? "" : "s"}. La recherche porte uniquement sur les produits déjà chargés.`, loading: "Chargement des produits…", retry: "Réessayer", more: (count: number) => `Charger ${count} de plus`, loadingMore: "Chargement…", none: "Aucun produit n’est disponible dans cette catégorie.", matches: "Aucun produit chargé ne correspond à cette recherche.", select: "Sélectionnez un produit pour consulter ses informations actuelles.", open: (name: string) => `Ouvrir ${name}`, image: "Image du produit indisponible", out: "Rupture de stock", in: "En stock", detailLoading: "Chargement des informations actuelles…", unavailable: "Ce produit n’est plus disponible dans le catalogue.", problem: "Impossible de charger ce produit. Réessayez.", back: "Retour au direct", variants: "Options disponibles", description: "Description", noDescription: "Aucune description n’est disponible pour ce produit.",
    selectedProduct: "Produit sélectionné", seller: "Vendeur", sellerUnavailable: "Les informations du vendeur ne sont pas disponibles dans cette fiche catalogue.", delivery: "Livraison", deliveryBody: "La disponibilité de livraison est confirmée dans le flux commerce configuré.", governance: "Gouvernance", governanceBody: "La disponibilité et le paiement restent sous l’autorité d’Engine.", commerceSheet: "FICHE COMMERCE", commerceTitle: "Prêt pour le commerce", commerceBody: "Ce produit reste lié au flux commerce Engine actuel.", catalogPrice: "Prix catalogue", availability: "Disponibilité", openCommerce: "Ouvrir la fiche commerce", shareSignedOut: "Connectez-vous pour ouvrir la fiche commerce.", shareNoLive: "Lancez un direct pour créer un lien commerce.", shareOutOfStock: "Ce produit est en rupture de stock et ne peut pas être partagé.", imagePicker: (name: string) => `Images de ${name}`, viewImage: (index: number) => `Voir l’image ${index}`,
  },
} as const;

const errorText = (error: unknown) => error instanceof Error && error.message ? error.message : "The catalog is unavailable.";
const unavailable = (error: unknown) => /\b404\b|not found|deleted|unavailable/i.test(errorText(error));
const soldOut = (product: CatalogProduct) => product.stock <= 0 || /out[ -]?of[ -]?stock|sold[ -]?out|unavailable/i.test(product.stockStatus);

function ProductImage({ product, alt }: { product: CatalogProduct; alt: string }) {
  const [failed, setFailed] = useState(false); const source = product.images.find(image => image.trim());
  return source && !failed ? <img className="shop-product-image" src={source} alt="" onError={() => setFailed(true)} /> : <div className="shop-product-image shop-product-image--empty" role="img" aria-label={alt}><ImageOff aria-hidden="true" size={24} /></div>;
}
function DetailMedia({ product, alt, imagePicker, viewImage }: { product: CatalogProduct; alt: string; imagePicker: string; viewImage(index: number): string }) {
  const images = product.images.filter(image => image.trim()); const [active, setActive] = useState(0); const [failed, setFailed] = useState(false); useEffect(() => setActive(0), [product.id]); useEffect(() => setFailed(false), [active, product.id]);
  if (!images.length) return <div className="shop-detail-media shop-product-image--empty" role="img" aria-label={alt}><ImageOff aria-hidden="true" size={28} /></div>;
  return <div className="shop-detail-media">{failed ? <div className="shop-detail-media-fallback" role="img" aria-label={alt}><ImageOff aria-hidden="true" size={28} /></div> : <img src={images[active]} alt={product.name} onError={() => setFailed(true)} />}{images.length > 1 && <div className="shop-media-picker" aria-label={imagePicker}>{images.map((image, index) => <button key={image} className={index === active ? "is-active" : ""} type="button" aria-label={viewImage(index + 1)} aria-pressed={index === active} onClick={() => setActive(index)}><img src={image} alt="" /></button>)}</div>}</div>;
}

export function ShopWorkspace({ catalog, authenticated = true, accountEpoch = 0, selectedProductId, onSelectProduct, onReturnToLive, onShare, canShare, mode, locale = "en" }: ShopWorkspaceProps) {
  const copy = messages[locale]; const [products, setProducts] = useState<CatalogProduct[]>([]); const [page, setPage] = useState<CatalogPage | null>(null); const [category, setCategory] = useState(""); const [categories, setCategories] = useState<string[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(false); const [listError, setListError] = useState(""); const failedListRequest = useRef<{ page: number; category: string; replace: boolean } | null>(null); const [detail, setDetail] = useState<CatalogProduct | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState<"unavailable" | "error" | "">(""); const listRequest = useRef(0); const detailRequest = useRef(0); const accountIdentity = useRef(`${accountEpoch}:${authenticated}`);
  const loadPage = useCallback(async (nextPage: number, nextCategory: string, replace: boolean) => { if (mode !== "native" || !authenticated) return; const retry = failedListRequest.current; const target = retry && retry.category === nextCategory ? retry : { page: nextPage, category: nextCategory, replace }; failedListRequest.current = null; const request = ++listRequest.current; setLoading(true); setListError(""); try { const next = await catalog.list({ page: target.page, ...(target.category ? { category: target.category } : {}) }); if (request !== listRequest.current) return; setPage(next); setProducts(current => target.replace ? next.products : [...current, ...next.products.filter(product => !current.some(item => item.id === product.id))]); setCategories(current => [...new Set([...current, ...next.products.map(product => product.category?.trim()).filter((value): value is string => Boolean(value))])].sort((a, b) => a.localeCompare(b))); } catch (error) { if (request === listRequest.current) { setListError(errorText(error)); failedListRequest.current = target; } } finally { if (request === listRequest.current) setLoading(false); } }, [authenticated, catalog, mode]);
  useEffect(() => { const identity = `${accountEpoch}:${authenticated}`; const accountChanged = accountIdentity.current !== identity; accountIdentity.current = identity; failedListRequest.current = null; listRequest.current += 1; detailRequest.current += 1; if (accountChanged) { setSearch(""); setCategories([]); if (category) { setCategory(""); setProducts([]); setPage(null); setListError(""); return; } } if (mode === "preview" || !authenticated) { setProducts([]); setPage(null); setCategories([]); setListError(""); setDetail(null); setDetailLoading(false); setDetailError(""); return; } setProducts([]); setPage(null); setCategories([]); setListError(""); void loadPage(1, category, true); }, [accountEpoch, authenticated, category, loadPage, mode]);
  const loadDetail = useCallback(async (id: string) => { if (mode !== "native" || !authenticated) return; const request = ++detailRequest.current; setDetail(null); setDetailLoading(true); setDetailError(""); try { const product = await catalog.product(id); if (request === detailRequest.current) setDetail(product); } catch (error) { if (request === detailRequest.current) setDetailError(unavailable(error) ? "unavailable" : "error"); } finally { if (request === detailRequest.current) setDetailLoading(false); } }, [authenticated, catalog, mode]);
  useEffect(() => { if (!selectedProductId || mode !== "native" || !authenticated) { detailRequest.current += 1; setDetail(null); setDetailLoading(false); setDetailError(""); return; } void loadDetail(selectedProductId); }, [accountEpoch, authenticated, loadDetail, mode, selectedProductId]);
  const visible = useMemo(() => { const needle = search.trim().toLocaleLowerCase(); return needle ? products.filter(product => `${product.name} ${product.description || ""}`.toLocaleLowerCase().includes(needle)) : products; }, [products, search]); const hasMore = Boolean(page && page.page * page.perPage < page.total); const canUseShare = mode === "native" && authenticated && canShare && detail !== null && !soldOut(detail); const shareUnavailable = !authenticated ? copy.shareSignedOut : detail && soldOut(detail) ? copy.shareOutOfStock : copy.shareNoLive; const stockText = (product: CatalogProduct) => soldOut(product) ? copy.out : /^in[_ -]?stock$/i.test(product.stockStatus) ? copy.in : product.stockStatus || copy.in;
  const catalogLibrary = <section className="shop-library" aria-label={copy.eyebrow}><div className="shop-controls"><div><label htmlFor="shop-search">{copy.search}</label><Input id="shop-search" type="search" value={search} placeholder={copy.placeholder} onChange={event => setSearch(event.target.value)} /></div><div className="shop-category"><label htmlFor="shop-category">{copy.category}</label><select id="shop-category" value={category} onChange={event => { setSearch(""); setCategory(event.target.value); }}><option value="">{copy.all}</option>{categories.map(item => <option value={item} key={item}>{item}</option>)}</select></div><p className="shop-scope" aria-live="polite">{copy.scope(visible.length, products.length)}</p></div>{listError && <div className="shop-state shop-state--error" role="alert"><p>{listError}</p><Button variant="outline" onClick={() => void loadPage(page?.page || 1, category, products.length === 0)}>{copy.retry}</Button></div>}{loading && products.length === 0 ? <p className="shop-state" role="status"><LoaderCircle className="shop-spinner" aria-hidden="true" size={20} />{copy.loading}</p> : <>{visible.length ? <div className="shop-grid">{visible.map(product => <button className="shop-card" data-selected={product.id === selectedProductId || undefined} key={product.id} type="button" onClick={() => onSelectProduct(product.id)} aria-label={copy.open(product.name)}><ProductImage product={product} alt={copy.image} /><span className="shop-card-copy"><span className="shop-card-category">{product.category || "—"}</span><strong>{product.name}</strong><span className="shop-card-bottom"><span>{product.priceDisplay}</span><span className={soldOut(product) ? "shop-stock shop-stock--out" : "shop-stock"}>{stockText(product)}</span></span></span></button>)}</div> : <p className="shop-state">{products.length ? copy.matches : copy.none}</p>}{hasMore && <div className="shop-load-more"><Button variant="outline" disabled={loading} onClick={() => void loadPage((page?.page || 0) + 1, category, false)}>{loading ? copy.loadingMore : copy.more(Math.min(page?.perPage || 1, Math.max(0, (page?.total || 0) - products.length)))}</Button></div>}</>}</section>;
  const detailPanel = <aside className="shop-detail" aria-live="polite" aria-label={copy.selectedProduct}>{!selectedProductId && <p className="shop-state">{copy.select}</p>}{selectedProductId && detailLoading && <p className="shop-state" role="status"><LoaderCircle className="shop-spinner" aria-hidden="true" size={20} />{copy.detailLoading}</p>}{selectedProductId && detailError && <div className="shop-state shop-state--error" role="alert"><p>{detailError === "unavailable" ? copy.unavailable : copy.problem}</p><Button variant="outline" onClick={() => void loadDetail(selectedProductId)}>{copy.retry}</Button></div>}{detail && !detailLoading && <article className="shop-detail-content"><div className="shop-detail-media-column"><DetailMedia product={detail} alt={copy.image} imagePicker={copy.imagePicker(detail.name)} viewImage={copy.viewImage} /></div><div className="shop-detail-copy"><p className="shop-card-category">{detail.category || "—"}</p><h1>{detail.name}</h1><p className="shop-detail-price">{detail.priceDisplay}</p><p className={soldOut(detail) ? "shop-stock shop-stock--out" : "shop-stock"}>{stockText(detail)}</p><dl className="shop-truth-list"><div><dt>{copy.seller}</dt><dd>{copy.sellerUnavailable}</dd></div><div><dt>{copy.delivery}</dt><dd><Truck aria-hidden="true" size={17} />{copy.deliveryBody}</dd></div><div><dt>{copy.governance}</dt><dd><ShieldCheck aria-hidden="true" size={17} />{copy.governanceBody}</dd></div></dl><div className="shop-detail-rule" /><section className="shop-description"><h2>{copy.description}</h2><p>{detail.description || copy.noDescription}</p></section>{detail.variants && detail.variants.length > 0 && <section className="shop-options"><h2>{copy.variants}</h2><ul className="shop-variants">{detail.variants.map(variant => <li key={variant}>{variant}</li>)}</ul></section>}</div><section className="shop-commerce-sheet" aria-label={copy.commerceSheet}><p className="eyebrow">{copy.commerceSheet}</p><h2>{copy.commerceTitle}</h2><p>{copy.commerceBody}</p><dl className="shop-commerce-summary"><div><dt>{copy.catalogPrice}</dt><dd>{detail.priceDisplay}</dd></div><div><dt>{copy.availability}</dt><dd className={soldOut(detail) ? "shop-stock shop-stock--out" : "shop-stock"}>{stockText(detail)}</dd></div></dl><Button disabled={!canUseShare} onClick={() => onShare(detail.id)}><ShoppingBag size={18} />{copy.openCommerce}</Button>{!canUseShare && <p className="shop-share-hint">{shareUnavailable}</p>}<p className="shop-authority"><PackageCheck aria-hidden="true" size={15} />{copy.governanceBody}</p></section></article>}</aside>;
  const hasSelection = Boolean(selectedProductId);
  return <section className={`shop-workspace${hasSelection ? " shop-workspace--selected" : ""}`} aria-label={hasSelection ? copy.selectedProduct : undefined} aria-labelledby={hasSelection ? undefined : "shop-heading"}><header className="shop-heading">{hasSelection ? <Button variant="ghost" className="shop-return" onClick={onReturnToLive}><ArrowLeft size={18} />{copy.back}</Button> : <div><p className="eyebrow">{copy.eyebrow}</p><h1 id="shop-heading">{copy.title}</h1></div>}</header>{mode === "preview" ? <p className="shop-state shop-preview" role="status">{copy.preview}</p> : <>{hasSelection && detailPanel}{catalogLibrary}{!hasSelection && detailPanel}</>}</section>;
}
